export const CandidateData = [
  {
    id: 1,
    name: "Ho Thanh Son",
    dateOfBirth: "1999-03-07",
    location: "Ho Chi Minh City",
    occupation: "Software Engineer",
    seniority: "JUNIOR",
    gpa: 3.1,
  },
  {
    id: 2,
    name: "Tran Van Dino",
    dateOfBirth: "1991-11-02",
    location: "Ho Chi Minh City",
    occupation: "Hr",
    seniority: "FRESHER",
    gpa: 3.7,
  },
  {
    id: 3,
    name: "Johny Deep",
    dateOfBirth: "1977-11-07",
    location: "Texas",
    occupation: "Tester",
    seniority: "SENIOR",
    gpa: 2.4,
  },
  {
    id: 4,
    name: "Tony Bush",
    dateOfBirth: "1972-10-21",
    location: "Washington.DC",
    occupation: "Product Owner",
    seniority: "SENIOR",
    gpa: 1.8,
  },
  {
    id: 5,
    name: "Nguyen Thi Hanh",
    dateOfBirth: "1985-02-28",
    location: "Can Tho City",
    occupation: "Technical Manager",
    seniority: "MANAGER",
    gpa: 2.4,
  },
  {
    id: 6,
    name: "Jirathip Soongthanenii",
    dateOfBirth: "1959-09-17",
    location: "PhnomPenh City",
    occupation: "Product Owner",
    seniority: "TEAM_LEAD",
    gpa: 1.7,
  },
  {
    id: 7,
    name: "Ahmut Halah",
    dateOfBirth: "1989-02-01",
    location: "Dubai City",
    occupation: "Tester",
    seniority: "MID_LEVEL",
    gpa: 2.6,
  },
  {
    id: 8,
    name: "Goerge Cruise",
    dateOfBirth: "1972-02-14",
    location: "Perth City",
    occupation: "DevOps Engineer",
    seniority: "DIRECTOR",
    gpa: 2.2,
  },
  {
    id: 9,
    name: "Mupalla Hen",
    dateOfBirth: "2001-03-31",
    location: "Victoria City",
    occupation: "Software Engineer",
    seniority: "INTERN",
    gpa: 3.3,
  },
  {
    id: 10,
    name: "Tonschovky Sheva",
    dateOfBirth: "2003-08-03",
    location: "Kiev City",
    occupation: "Scum Master",
    seniority: "JUNIOR",
    gpa: 2.5,
  },
];
